//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstTW.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON
    {
        public string ID { get; set; }
        public string FULLNAME { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<decimal> SALARY { get; set; }
        public string NOTE { get; set; }
        public Nullable<decimal> DEPARTMENTID { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
    }
}
